"""
RMI Tool Tier System
=====================
Three-tier classification aligned with scan pack pricing:

    BASIC   ($0.01-0.02) — Quick scans, lookups, health checks
    PREMIUM ($0.05-0.10) — Advanced analysis, multi-source intelligence
    ELITE   ($0.15-0.40) — Institutional forensic investigation

All descriptions are SOURCE-FREE — we describe what the tool DOES,
never where the data comes from. Every tool has a unique, original name
that sells the intelligence value, not the data pipeline.

Tier logic:
    Basic: Single-focus, fast, high-volume, low compute
    Premium: Multi-source synthesis, pattern detection, deeper analysis
    Elite: Comprehensive investigation, institutional reports, advanced forensics
"""

# ── Complete tool tier classification ──────────────────────────

TOOL_TIERS = {
    # ═══ BASIC TIER ($0.01-0.02) — Quick Scans & Lookups ═══
    "urlcheck": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "URL Threat Scanner",
        "description": "Instant domain safety verification. Detects phishing sites, fake project pages, wallet drainers, and malicious redirects through structural analysis and behavioral fingerprinting — no blacklists needed.",
        "trial_free": 3,
    },
    "pulse": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Market Pulse Monitor",
        "description": "Real-time token momentum dashboard. Tracks volume surges, price action anomalies, whale movement alerts, and trending tokens across all major trading venues simultaneously.",
        "trial_free": 3,
    },
    "token_age": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Token Age Verifier",
        "description": "Verify exact token creation timestamp and age. Identifies freshly minted tokens versus established assets to flag potential pump-and-dump launches before you invest.",
        "trial_free": 3,
    },
    "tw_profile": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Social Profile Inspector",
        "description": "Retrieve full social media profile data including verification status, follower metrics, account age, and engagement patterns to assess project team credibility.",
        "trial_free": 3,
    },
    "tw_timeline": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Social Timeline Viewer",
        "description": "Access recent posts and activity history from any social media account. Track what project teams and influencers are saying in real-time.",
        "trial_free": 3,
    },
    "tw_search": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Social Intelligence Search",
        "description": "Search across social platforms for keywords, cashtags, and project mentions. Discover what the community is discussing before it impacts market prices.",
        "trial_free": 3,
    },
    "scam_database": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Scam Registry Lookup",
        "description": "Query our continuously updated database of known scam tokens, fraudulent contracts, and blacklisted addresses. Instant yes/no with risk classification.",
        "trial_free": 5,
    },
    "gas_forecast": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Network Cost Forecaster",
        "description": "Real-time gas fee prediction across all major networks. Optimize transaction timing to save on network costs with confidence-scored recommendations.",
        "trial_free": 3,
    },
    "chain_health": {
        "tier": "basic",
        "price_usd": 0.01,
        "name": "Chain Health Monitor",
        "description": "Comprehensive blockchain network status including total value locked, node health, congestion metrics, and recent activity statistics across all supported networks.",
        "trial_free": 3,
    },
    "market_overview": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "Market Landscape Overview",
        "description": "Bird's-eye view of the entire crypto market — major asset prices, dominance metrics, total value locked trends, and sector performance breakdowns.",
        "trial_free": 3,
    },
    "rugshield": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "RugShield Quick Scan",
        "description": "Pre-purchase safety check. Binary safe/unsafe verdict based on liquidity analysis, holder distribution, contract verification, and deployer history in under 3 seconds.",
        "trial_free": 3,
    },

    # ═══ PREMIUM TIER ($0.05-0.10) — Advanced Intelligence ═══
    "audit": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Deep Contract Auditor",
        "description": "100-point forensic contract examination. Analyzes tokenomics structure, permission controls, liquidity mechanisms, holder concentration, and hidden backdoors. Comprehensive security scoring with actionable findings.",
        "trial_free": 1,
    },
    "wallet": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Wallet Intelligence Profiler",
        "description": "Complete wallet behavioral analysis. Identifies trading patterns, persona classification (bot/retail/institution/insider), profit-and-loss history, and risk profile with confidence scoring.",
        "trial_free": 1,
    },
    "smartmoney": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Alpha Flow Tracker",
        "description": "Track capital movements of proven profitable wallets across all chains. Identifies accumulation patterns, exit signals, and emerging trends before they become obvious to the market.",
        "trial_free": 1,
    },
    "whale_scan": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Whale Movement Surveillance",
        "description": "Real-time large-holder transaction monitoring. Detects whale accumulation, distribution, and coordinated movements. Alerts on unusual activity patterns that precede major price movements.",
        "trial_free": 1,
    },
    "whale_profile": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Whale Identity Profiler",
        "description": "Deep-dive into large wallet holder identities. Maps exchange affiliations, institutional connections, historical trading style, and multi-chain footprint for comprehensive whale intelligence.",
        "trial_free": 1,
    },
    "cluster": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Syndicate Network Mapper",
        "description": "Advanced wallet clustering analysis. Detects coordinated wallet groups, Sybil attack patterns, hidden insider networks, and cross-chain relationships that indicate organized market manipulation.",
        "trial_free": 1,
    },
    "insider": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Insider Activity Detector",
        "description": "Track developer and team wallet activity across all their projects. Flags insider selling patterns, team token movements, and suspicious pre-announcement trading behavior.",
        "trial_free": 1,
    },
    "syndicate_scan": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Organized Group Scanner",
        "description": "Detect coordinated trading groups manipulating token prices. Analyzes transaction timing patterns, wallet relationships, and synchronized buy/sell behavior to expose organized pump operations.",
        "trial_free": 1,
    },
    "syndicate_track": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Group Activity Monitor",
        "description": "Continuous surveillance of known manipulation groups. Tracks their current targets, position changes, and emerging strategies across multiple tokens simultaneously.",
        "trial_free": 1,
    },
    "wallet_graph": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Transaction Web Analyzer",
        "description": "Visualize and analyze the complete transaction network around any wallet. Discovers hidden connections, funding sources, and counterparty relationships that reveal true wallet identity and intent.",
        "trial_free": 1,
    },
    "sniper_detect": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Bot Activity Detector",
        "description": "Identify automated trading bot patterns in token markets. Detects sniper bots, MEV extractors, and algorithmic traders. Quantifies bot vs human trading ratio for any token.",
        "trial_free": 1,
    },
    "sniper_alert": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Early Entry Alert System",
        "description": "Real-time alerts when sniper bots and automated systems begin accumulating a token. Get notified before the crowd when algorithmic traders identify opportunity.",
        "trial_free": 2,
    },
    "copy_trade_finder": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Profit Mirror Discovery",
        "description": "Identify the most consistently profitable wallets to emulate. Ranks traders by win rate, risk-adjusted returns, and strategy consistency across multiple market cycles.",
        "trial_free": 1,
    },
    "liquidity_flow": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Capital Flow Tracker",
        "description": "Monitor liquidity movements across trading venues and protocols. Detects capital rotation patterns, liquidity migrations, and emerging sector trends before price discovery.",
        "trial_free": 1,
    },
    "liquidity_depth": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Market Depth Analyzer",
        "description": "Assess true market depth beyond the spread. Reveals hidden liquidity walls, potential slippage points, and genuine versus spoofed order book activity.",
        "trial_free": 2,
    },
    "sentiment": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Market Sentiment Engine",
        "description": "Multi-platform sentiment analysis aggregating social media, community discussions, and news sources. Quantifies bullish vs bearish sentiment with historical trend comparison.",
        "trial_free": 2,
    },
    "sentiment_spike": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Sentiment Surge Detector",
        "description": "Real-time detection of abnormal sentiment shifts. Flags coordinated social campaigns, sudden narrative changes, and viral attention spikes that often precede major price moves.",
        "trial_free": 1,
    },
    "social_signal": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Influence Signal Processor",
        "description": "Advanced social media signal analysis with influence weighting and authenticity scoring. Separates genuine community sentiment from paid promotion and bot activity.",
        "trial_free": 1,
    },
    "kol_performance": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Influencer Track Record",
        "description": "Analyze historical performance of crypto influencers and key opinion leaders. Tracks call accuracy, average returns, and post-impact timing to identify who actually moves markets.",
        "trial_free": 1,
    },
    "token_deep_dive": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Token Deep Investigation",
        "description": "Comprehensive token due diligence combining holder analysis, liquidity assessment, team background verification, and risk factor identification into a single detailed report.",
        "trial_free": 1,
    },
    "token_comparison": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Asset Comparison Matrix",
        "description": "Side-by-side analysis comparing any two tokens across security metrics, market performance, holder quality, and growth potential. Data-driven ranking for investment decisions.",
        "trial_free": 1,
    },
    "honeypot_check": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Trade Lock Detector",
        "description": "Detect honeypot contracts that block selling. Simulates buy and sell transactions to verify token tradability. Identifies hidden transfer restrictions and blacklist mechanisms.",
        "trial_free": 2,
    },
    "risk_monitor": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Portfolio Risk Sentinel",
        "description": "Continuous risk monitoring for any token or wallet. Tracks liquidity changes, holder concentration shifts, and security events. Alerts on deteriorating conditions before losses occur.",
        "trial_free": 2,
    },
    "anomaly": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Market Anomaly Detector",
        "description": "Statistical anomaly detection across trading patterns. Flags wash trading, volume manipulation, artificial price support, and other market irregularities invisible to basic scanners.",
        "trial_free": 1,
    },
    "bridge_security": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Cross-Chain Bridge Monitor",
        "description": "Monitor bridge security across all major protocols. Tracks total value locked, recent exploits, vulnerability disclosures, and anomalous withdrawal patterns that signal bridge attacks.",
        "trial_free": 1,
    },
    "mev_protection": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "MEV Shield Analysis",
        "description": "Assess your transaction's vulnerability to MEV extraction. Identifies sandwich attack risks, front-running exposure, and provides actionable protection strategies for your specific trade.",
        "trial_free": 1,
    },
    "mev_alert": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Extraction Activity Monitor",
        "description": "Real-time MEV activity tracking across trading venues. Alerts on abnormal extraction patterns, new attack vectors, and high-risk trading periods to avoid.",
        "trial_free": 2,
    },
    "wash_trading": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Volume Authenticity Verifier",
        "description": "Detect artificial trading volume through pattern analysis. Identifies wash trading circles, self-trading schemes, and volume inflation tactics used to mislead investors.",
        "trial_free": 1,
    },
    "nft_wash_detector": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "NFT Market Integrity Scan",
        "description": "Specialized wash trading detection for NFT collections. Analyzes sale patterns, floor price manipulation, and coordinated bidding behavior to reveal authentic vs artificial demand.",
        "trial_free": 1,
    },
    "defi_yield_scanner": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Yield Opportunity Scanner",
        "description": "Scan for the best risk-adjusted yield opportunities across all protocols. Sustainability analysis, protocol health checks, and historical APY stability scoring included.",
        "trial_free": 2,
    },
    "launch": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "New Token Discovery Engine",
        "description": "Detect newly launched tokens within seconds of creation. Risk-scored launch analysis identifying potential gems versus likely scams based on deployment patterns and initial liquidity.",
        "trial_free": 2,
    },
    "launch_intel": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Launch Intelligence Brief",
        "description": "Pre-launch and early-launch intelligence gathering. Team verification, tokenomics assessment, community authenticity scoring, and comparative analysis against similar launches.",
        "trial_free": 1,
    },
    "airdrop_finder": {
        "tier": "premium",
        "price_usd": 0.05,
        "name": "Airdrop Opportunity Locator",
        "description": "Discover high-value airdrop opportunities from protocols without tokens. Analyzes protocol maturity, user base, and tokenomics likelihood to rank airdrop potential.",
        "trial_free": 2,
    },
    "airdrop_check": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "Wallet Eligibility Checker",
        "description": "Check any wallet address for unclaimed airdrops, reward distributions, and protocol incentives across all supported networks. Never leave value unclaimed.",
        "trial_free": 3,
    },
    "portfolio_tracker": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Multi-Wallet Portfolio View",
        "description": "Aggregated portfolio tracking across unlimited wallet addresses. Real-time balance aggregation, performance metrics, and asset allocation breakdown in a single unified dashboard.",
        "trial_free": 1,
    },
    "portfolio_aggregate": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Cross-Chain Wealth Analysis",
        "description": "Comprehensive net worth calculation spanning all blockchains. Discovers hidden assets, forgotten wallets, and unclaimed value through deep chain inspection.",
        "trial_free": 1,
    },
    "wallet_pnl": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Trading Performance Auditor",
        "description": "Calculate realized and unrealized profit/loss for any wallet. Tracks entry/exit timing, win rate analysis, and strategy classification to understand exactly how money was made or lost.",
        "trial_free": 1,
    },
    "arbitrage_scan": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Cross-Venue Price Scanner",
        "description": "Identify price discrepancies across trading venues. Real-time arbitrage opportunity detection with profit calculation after estimated fees and slippage.",
        "trial_free": 1,
    },
    "whale_accumulation": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Accumulation Pattern Detector",
        "description": "Detect stealth accumulation by large holders before price impact. Identifies quiet buying patterns, OTC accumulation signals, and wallet funding sequences that precede major positions.",
        "trial_free": 1,
    },
    "unlock_calendar": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "Token Unlock Scheduler",
        "description": "Track upcoming token unlock events across all major protocols. Impact assessment, supply dilution calculation, and historical unlock price action analysis.",
        "trial_free": 3,
    },
    "listing_predictor": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Exchange Listing Forecaster",
        "description": "Predict likely exchange listings based on accumulation patterns, wallet connections, and historical listing behavior. Scores confidence for each major exchange.",
        "trial_free": 1,
    },
    "alpha_digest": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Alpha Intelligence Digest",
        "description": "Curated summary of highest-confidence alpha signals across all intelligence tools. Whale movements, insider activity, sentiment shifts, and emerging trends in one actionable brief.",
        "trial_free": 1,
    },
    "insider_network": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Insider Web Mapper",
        "description": "Map the complete network of insider-connected wallets. Reveals shared funding sources, coordinated trading rings, and team-to-team relationships across multiple projects.",
        "trial_free": 1,
    },
    "protocol_risk": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Protocol Security Auditor",
        "description": "Comprehensive DeFi protocol risk assessment. Smart contract risk, governance vulnerability, oracle dependency, and economic exploit vector analysis with severity scoring.",
        "trial_free": 1,
    },
    "profile_flip": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Identity Change Detector",
        "description": "Detect when project teams or wallets change their on-chain behavior patterns. Flags sudden strategy shifts, new wallet activations, and behavioral pivots that signal upcoming changes.",
        "trial_free": 1,
    },
    "fresh_pair": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "New Market Scanner",
        "description": "Discover newly created trading pairs within minutes. Risk-ranked listing of fresh markets with initial liquidity assessment and deployer history verification.",
        "trial_free": 3,
    },
    "clone_detect": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Token Clone Detector",
        "description": "Identify cloned and copycat tokens. Detects contract code duplication, branding imitation, and impersonation attempts designed to deceive investors.",
        "trial_free": 1,
    },
    "deployer_history": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Creator Track Record",
        "description": "Investigate the complete deployment history of any token creator address. Success rate, previous rug pulls, total value created or destroyed, and risk classification.",
        "trial_free": 1,
    },
    "liquidity_migration": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Liquidity Movement Tracker",
        "description": "Track liquidity migrations between trading venues. Identifies projects moving to new platforms, abandoning old pools, or preparing for token migrations.",
        "trial_free": 1,
    },
    "bundler_detect": {
        "tier": "premium",
        "price_usd": 0.08,
        "name": "Supply Manipulation Detector",
        "description": "Detect bundled token launches where insiders control disproportionate supply. Identifies sniper-controlled distributions and pre-minted manipulation setups.",
        "trial_free": 1,
    },
    "rug_pull_predictor": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Exit Scam Forecaster",
        "description": "Predictive model identifying tokens at high risk of rug pull. Multi-signal analysis combining liquidity patterns, holder behavior, deployer history, and social signals for early warning.",
        "trial_free": 1,
    },
    "smart_money_alpha": {
        "tier": "premium",
        "price_usd": 0.10,
        "name": "Elite Wallet Tracker",
        "description": "Track the highest-performing wallets filtered by consistency and risk management. Focuses on sustainable alpha generation rather than one-hit wonders.",
        "trial_free": 1,
    },
    "meme_vibe_score": {
        "tier": "basic",
        "price_usd": 0.02,
        "name": "Community Energy Meter",
        "description": "Quantify meme coin community strength through engagement velocity, viral coefficient, and organic growth signals. Separates genuine community energy from paid hype.",
        "trial_free": 3,
    },

    # ═══ ELITE TIER ($0.15-0.40) — Institutional Investigation ═══
    "forensics": {
        "tier": "elite",
        "price_usd": 0.10,
        "name": "Forensic Investigation Suite",
        "description": "Comprehensive token forensic analysis combining deep contract examination, holder profiling, liquidity analysis, and risk scoring into an institutional-grade investigation report.",
        "trial_free": 1,
    },
    "whale": {
        "tier": "elite",
        "price_usd": 0.15,
        "name": "Whale Deep Investigation",
        "description": "Advanced whale wallet analysis with complete identity profiling, multi-chain footprint mapping, exchange relationship discovery, and predictive behavior modeling. The gold standard in whale intelligence.",
        "trial_free": 1,
    },
    "forensic_valuation": {
        "tier": "elite",
        "price_usd": 0.25,
        "name": "Institutional Valuation Model",
        "description": "Discounted cash flow and comparable analysis valuation for any token. Intrinsic value calculation, peer benchmarking with outlier detection, and scam probability scoring. Institutional-grade methodology adapted for digital assets.",
        "trial_free": 1,
    },
    "osint_identity_hunt": {
        "tier": "elite",
        "price_usd": 0.15,
        "name": "Identity Investigation Service",
        "description": "Cross-platform identity investigation hunting usernames, domains, and digital footprints across hundreds of networks. Stealth reconnaissance with comprehensive link analysis.",
        "trial_free": 2,
    },
    "investigation_report": {
        "tier": "elite",
        "price_usd": 0.20,
        "name": "Complete Investigation Report",
        "description": "Full-spectrum investigation combining on-chain forensics, financial valuation modeling, digital identity research, and risk assessment into a single comprehensive deliverable. Ready for due diligence or legal review.",
        "trial_free": 1,
    },

    # ═══ BUNDLES (discounted packs) ═══
    "forensic_pack": {
        "tier": "elite",
        "price_usd": 0.40,
        "name": "Forensic Investigation Pack",
        "description": "Complete investigation bundle: Institutional Valuation + Identity Investigation + Full Report. 33% savings versus individual purchases. Everything needed for comprehensive due diligence.",
        "trial_free": 1,
    },
    "security_pack": {
        "tier": "premium",
        "price_usd": 0.15,
        "name": "Security Intelligence Pack",
        "description": "Essential security bundle: Deep Contract Audit + RugShield Scan + Trade Lock Detection + Exit Scam Risk Assessment. Comprehensive protection in one discounted package.",
        "trial_free": 1,
    },
    "intelligence_pack": {
        "tier": "premium",
        "price_usd": 0.15,
        "name": "Alpha Intelligence Pack",
        "description": "Complete intelligence bundle: Wallet Profiler + Alpha Flow Tracker + Whale Surveillance + Insider Detection. Full market intelligence suite at a bundled discount.",
        "trial_free": 1,
    },
    "all_in_one": {
        "tier": "elite",
        "price_usd": 0.25,
        "name": "Complete Analysis Bundle",
        "description": "Everything-in-one: Security scan, wallet intelligence, market analysis, and social sentiment. The ultimate crypto investigation tool. Best value for comprehensive research.",
        "trial_free": 1,
    },
}

# Tier pricing and scan pack alignment
TIER_PRICING = {
    "basic": {
        "name": "Basic",
        "price_range": "$0.01 - $0.02",
        "subscription_equivalent": "Free / Basic",
        "scan_pack_equivalent": "$5 Scan Pack",
        "description": "Quick scans, lookups, and health checks. High volume, low cost. Perfect for initial research.",
    },
    "premium": {
        "name": "Premium",
        "price_range": "$0.05 - $0.10",
        "subscription_equivalent": "Pro / Pro+",
        "scan_pack_equivalent": "$10 Scan Pack",
        "description": "Advanced analysis, multi-source intelligence synthesis, and pattern detection. For serious traders and investigators.",
    },
    "elite": {
        "name": "Elite",
        "price_range": "$0.10 - $0.40",
        "subscription_equivalent": "Elite",
        "scan_pack_equivalent": "$15 Scan Pack",
        "description": "Institutional-grade forensic investigation, identity research, and comprehensive reports. Maximum depth, maximum value.",
    },
}
